apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudproductos
spec:
  replicas: 3
  selector:
    matchLabels:
      role: crudproductos
  template:
    metadata:
      labels:
        role: crudproductos
    spec:
      containers:
      - name: crudproductos
        image: alfredochusgodev/modulo_10:v2.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: crudproductos
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31112
  selector:
    role: crudproductos
  type: LoadBalancer
